Update GA_on_GHRunner.yml

diff --git a/.github/workflows/GA_on_GHRunner.yml b/.github/workflows/GA_on_GHRunner.yml
--- a/.github/workflows/GA_on_GHRunner.yml
+++ b/.github/workflows/GA_on_GHRunner.yml
@@ -26,17 +26,18 @@ jobs:
           format: markdown
           hide_complexity: true
 
-      - name: Update README.md with Coverage Badge
+      - name: Read Coverage Output
+        id: read_coverage
         run: |
-          # Extract the URL using a regex
-          # url=$(echo "${{ steps.coverage.outputs.stdout }}" | grep -oP '(?<=\!\[Code Coverage\]\().*?(?=\))')
-          # Output the extracted URL
-          echo "${{ steps.coverage.outputs.* }}"
-      #     # Define the badge URL (adjust the URL according to your badge)
-      #     BADGE_URL="${{ steps.coverage.output }}"
-      #     # Update README.md
-      #     echo "![Test Coverage]($BADGE_URL)" >> README.md
-
+          # Read the output file generated by the action
+          if [ -f code-coverage-results.md ]; then
+          output=$(cat coverage/coverage.md)
+          echo "coverage_output=$output" >> $GITHUB_ENV  # Set the output as an environment variable
+          else
+          echo "Coverage output file not found!"
+          exit 1
+          fi
+          
       # - name: Commit and Push Changes
       #   run: |
       #     git config --local user.email "action@github.com"
